### ISSUE TITLE
README would benefit by including `Resolver` specification

### ISSUE THREAD

**Issue by metasim** [eltimn/sbt-frontend#1]
Plugin isn't found in the default resolvers. Looks like this should do this trick:

```scala
resolvers += Resolver.bintrayIvyRepo("eltimn", "sbt-plugins")
```

Also looks like `0.1.1` is the latest release, not `0.1.0`.

**Comment by eltimn** [comment]
I updated the version on the readme and this is now in the community plugins, so the resolver is not needed anymore.
